name: RPM
description: "Progettino di APPM"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  http: ^1.2.0
  geocoding: ^3.0.0
  file_picker: ^8.0.1
  image_picker: ^1.0.7
  audioplayers: ^6.0.0
  audio_service: ^0.18.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: lib/oggetti/fonts/MyFlutterApp.ttf

  assets:
    - lib/localization/